fixed icons size
appwrite/pink pull request #134
Opened 2023-12-21 17:53 UTC by amanr-dev

## What does this PR do?

### The size of the icons was so small. So in this PR, the icon's size is fixed.

2023-12-21 17:55 UTC, amanr-dev commented
For the example

Before :
![Screenshot 2023-12-21 232352](https://github.com/appwrite/pink/assets/124811276/e28345c0-3534-4acd-858e-61b40d441b82)

After : 
![Screenshot 2023-12-21 232415](https://github.com/appwrite/pink/assets/124811276/2b3c3d9c-9247-42bf-97cc-8ac50243e7b6)

2024-01-06 10:00 UTC, amanr-dev commented
Hi @TorstenDittmann , please review the PR.

2024-02-07 12:56 UTC, TorstenDittmann approved these changes

2024-02-07 12:58 UTC, TorstenDittmann requested changes

2024-02-07 13:50 UTC, amanr-dev commented on packages/icons/scripts.js
> +      fontSize: "22px",
Ok, I will change this to the previous size.

2024-02-07 14:04 UTC, amanr-dev commented on packages/icons/scripts.js
> +      fontSize: "22px",
I am working on it

2024-02-08 16:55 UTC, amanr-dev commented on packages/icons/scripts.js
> +      fontSize: "22px",
Added font size to the icons individually.

2024-02-08 16:57 UTC, amanr-dev commented
Hi @TorstenDittmann, now you can review the PR

2024-08-19 07:31 UTC, closed without merging