Updated the setup guidelines in contributing.md
appwrite/pink pull request #72
Opened 2023-03-21 04:46 UTC by ItsRoy69

## What does this PR do?

When we visit https://github.com/appwrite/pink/blob/main/CONTRIBUTING.md made the changes in CONTRIBUTING.md's setup guidelines

## Related PRs and Issues

#71

### Have you read the [Contributing Guidelines on issues]

Yes

2023-03-21 11:11 UTC, ArmanNik approved these changes

2023-03-29 17:20 UTC, arimallick approved these changes

2023-04-03 21:34 UTC, TGlide requested changes
Thank you for the contribution! Just a small change required 😄

2023-04-03 21:34 UTC, TGlide commented on CONTRIBUTING.md
> +git clone https://github.com/appwrite/pink.git
```suggestion
git clone https://github.com/appwrite/pink.git
cd pink
```
We should probably keep the `cd` command 🙂

2023-04-18 19:07 UTC, TGlide approved these changes

2023-04-18 19:07 UTC, merged